spring:
  application:
    name: Simple E-commerce API

  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



security:
  jwt:
    secret_key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration_time: 3600000 # 1 hour